version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    labels:
      - dependencies
      - java
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: "/src/main/frontend"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    labels:
      - dependencies
      - frontend
    open-pull-requests-limit: 10
