springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
  api-docs:
    enabled: true
    path: /v3/api-docs

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

logging:
  level:
    com.wtechitsolutions: DEBUG
    org.springframework.batch: INFO
    org.springframework.web: DEBUG
